#  名字需要是 .jazzy.yaml  
# jazzy 直接运行   
# sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer 
# xcode-select -print-path
clean:  

module: TKNetworkEyeModule 
module_version: 0.1.2 
root_url: https://github.com/zhuamaodeyu
author: 抓猫的鱼
author_url: https://github.com/zhuamaodeyu/knowledge
github_url: https://github.com/zhuamaodeyu/TKAuthorityModule.git
 

title: TKComponentization/TKNetworkEyeModule 
readme: ../README.md  


theme: apple  
output: out/doc

copyright: '© 2018 [抓猫的鱼](https://github.com/zhuamaodeyu/knowledge) under
          [open source license](https://github.com/zhuamaodeyu/TKNetworkEyeModule/blob/master/LICENSE).'


# xcodebuild arguments 
# xcodebuild_arguments: ["-workspace","TKAuthorityModule.xcworkspace",
#                         "-scheme","TKAuthorityModule","-sdk","iphonesimulator"]

xcodebuild_arguments:
  - -workspace
  - TKNetworkEyeModule.xcworkspace
  - -scheme
  - TKNetworkEyeModule
  - -sdk 
  - iphonesimulator


hide_documentation_coverage: true 
documentation: xxxx/*.md  # 都可 
skip_undocumented: true   


# docset 
# docset_icon: xxxx/xxx
# docset_path: xxx/xxx 


swift_version: 5.0.1
min_acl: public  # public open, fileprivate, intxxx 

# exclude:  
#   - "xxxxx.swift"  
#   - "xxxx.swift" 
  
  
custom_categories:  
  - name: Manager 
    children:  
      - NetworkEyeManager 
  - name: Enum 
    children:
      - CleanupStrategyType 
  - name: Config 
    children:
      - NetworkEyeConfig



